# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Em',
            new_name='Expenses',
        ),
    ]
